cryptocgt:
  config:
    buysSellsCSV: /Users/Hayden Dekker/OneDrive/Professional/Tax/2023/Hayden/Crypto/orderhistory.csv
    sendsReceivesCSV: /Users/Hayden Dekker/OneDrive/Professional/Tax/2023/Hayden/Crypto/sendsreceives.csv
    reportLocation: /Users/Hayden Dekker/OneDrive/Professional/Tax/2023/Hayden/Crypto/report.csv

